services:
  # Frontend Service (Static React App)
  - type: web
    name: pool-villa-frontend
    env: static
    plan: free
    region: singapore
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://pool-villa-backend.onrender.com

  # Backend Service (Node.js/Express API)
  - type: web
    name: pool-villa-backend
    env: node
    plan: free
    region: singapore
    buildCommand: |
      cd backend
      npm install
    startCommand: |
      cd backend
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000